name: Mark Lalor
description: >
    Mark Lalor
about: >
    I am a third-year Computer Science major at Case Western Reserve University, with interest and artificial intelligence and computer
    networks, and am currently involved in DNS-focused networks research this fall. At CWRU I work with the local ACM chapter to put on
    events on campus to promote and teach CS on campus. I am also the current maintainer of the Hacker Society weekly tech-talk series.
    Feel free to send me an email at markwlalor@gmail.com

master_repo: false
url: https://marklalor.com
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo: logo.png

rtl: false
owner:
  name: Mark Lalor
  avatar: https://avatars0.githubusercontent.com/u/8631708?s=230
  email: markwlalor@gmail.com
  github: https://github.com/marklalor
  linkedin: https://www.linkedin.com/in/marklalor

rss: true

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
